اصلاح مستندات مهندسی نرم‌افزار فازهای 1 تا 6
Star-Academy/codestar-documents pull request #1
Opened 2022-07-11 11:01 UTC by RAAvenger

2022-07-11 12:36 UTC, mostmand requested changes
دمتون گرم
فایل‌های اسکرین‌شات خوبه که فقط قسمت وبسایت نمایش داده بشه و تب‌های مرورگر با کراپ حذف بشن.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +با اجرای دستور بالا باید عبارت `Hello World`
خوب است یک باکس برای خروجی کدها در نظر گرفته شود و این‌جا بنویسیم باید خروجی به صورت زیر باشد

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +و نیز اطلاعات خود آن می‌باشد.  این ابزار، مکانیزم‌هایی برای ایجاد، نگهداری و استفاده از کدها ارائه می‌دهد که برای هرکدام از این مکانیزم‌ها ابزارهایی نیز فراهم کرده‌است. هنگام استفاده از NuGet
اطلاعات خود آن یعنی چه؟
هم چنین کلمه‌ی نیز در این جا چندان قشنگ نیست

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +توسعه دهنده نگران دریافت و اشتراک کدها نمی‌باشد چرا که خود NuGet
نیم فاصله در توسعه دهنده رعایت نشده است

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +```C#
درست آن
"```csharp"
است

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +```C#
در جاهای دیگر نیز این ایراد وجود دارد که دیگر کامنت نگذاشتم

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +- [Console.ReadLine() Method in C#](<https://www.geeksforgeeks.org/console-readline-method-in-c-sharp/#:~:text=Console.-,ReadLine()%20Method%20in%20C%23,user%20presses%20the%20Enter%20key.>)
در داکیومنتی که در docusaurus نمایش داده می‌شود علامت شارپ در انتهای سی‌شارپ به اشتباه در ابتدای سطر نمایش داده می‌شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +یکی از گام‌های مهم یادگیری هر زبان برنامه‌نویسی یادگیری اصول نام‌گذاری زبان می‌باشد. شاید نام‌گذاری در وهله اول مورد مهمی به نظر نرسد اما این موضوع از جهتی اهمیت دارد که نباید کد شما نسبت به کدهای جا
یکی از گام‌های مهم یادگیری هر زبان برنامه‌نویسی یادگیری اصول نام‌گذاری *آن* می‌باشد.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +### Extension Method
به نظرم مبحث مهمی نیست
هم‌چنین اگر می‌خواهید این مبحث را مطرح کنید حتماً به syntactic sugar بودن آن اشاره کنید.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +برنامه‌ای بنویسید که دو فایل [دانشجویان](/static/datasets/scores.json)
لینک فایل‌ها خراب است فایل‌ها در این آدرس موجود نیستند

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +یا [Rider](https://soft98.ir/software/programming/1016-%D8%AF%D8%A7%D9%86%D9%84%D9%80%D9%88%D8%AF-%D9%86%D8%B1%D9%85-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-%D8%B1%D8%A7%DB%8C%D9%80%D9%80%D8%AF%D8%B1.html)
چرا ویژوال استودیو از سایت خود مایکروسافت رفرنس داده شده ولی Rider از soft98؟
روی گیت‌هاب هستیم مشکل کپی‌رایت نخوریم؟

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase04-unit-test.md
> +## تاثیر اصول SOLID بر Unit Tesing
تأکید بیش‌تری روی SOLID انجام بشه مثلاً بگید
دانستن اصول SOLID برای برنامه‌نویس‌ها از نان شب واجب‌تر است.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase04-unit-test.md
> +کردن است که در آن، قسمتی از کد را با یک پیاده‌سازی دلخواه جایگزین می‌کنیم و از آن برای شبیه‌سازی یک عملیات واقعی استفاده می‌شود. معمولا Mock
دو فعل جمله‌های عطف‌شده با هم سازگار نیست شاید به جای واو، حرف ربط "که" بگذاریم بهتر باشد

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase04-unit-test.md
> +برگرداند، به این معنی که ارسال با موفقیت انجام شده‌است. در نتیجه می‌توانیم عملکرد همان متد را تست کنیم، به جای این که بخواهیم درگیر وابستگی‌های آن نیز شویم.
کلمه‌ی "نیز" اضافه است.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase04-unit-test.md
> +و نحوۀ استفاده این تکنیک در زبان #C
همزه‌ی نشان ی میانجی انتهای کلمه‌ی "نحوه" با سایر جاها هم‌خوانی ندارد

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase04-unit-test.md
> +- [Getting started with moq](https://riptutorial.com/moq)
بهتر است به جای moq لایبرری NSubstitue را معرفی کنید

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +## بازنویسی پروژهٔ سرچ با زبان #C و با رویکرد TDD
ی میانجی انتهای کلمه‌ی "پروژه" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +در این مرحله، پروژهٔ سرچ خود را که قبلاً جاوا نوشته‌اید را بعنوان یک library
ی میانجی انتهای کلمه‌ی "پروژه" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +را به کار ببرید و آموخته‌های خود از مرحلهٔ قبل را اعمال کنید.
ی میانجی انتهای کلمه‌ی "مرحله" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +همچنین مراحل زیر را برای ساختن پروژهٔ خود دنبال کنید.
ی میانجی انتهای کلمه‌ی "پروژه" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +### ساختن یک پروژهٔ Class Library
ی میانجی انتهای کلمه‌ی "پروژه" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +در این مرحله یک پروژهٔ Net Class Library.
ی میانجی انتهای کلمه‌ی "پروژه" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +در این مرحله یک پروژه تست با فریم‌ورک XUnit
*xUnit

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +dotnet new XUnit -o .\SampleLibrary.Test
XUnit
به صورت
lowercase
نوشته شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +کد پروژهٔ شما، در پروژهٔ Class Libraryای
ی میانجی انتهای کلمه‌ی "پروژه" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase05-tdd.md
> +:::caution توجه
من اصلا جمله‌ای که در این توجه نوشته شده است را متوجه نشدم.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase06-cicd.md
> +و اهمیت استفاده از آن آشنا خواهید شد. همچنین پروژهٔ خود را به CI/CD
ی میانجی انتهای کلمه‌ی "پروژه" حذف شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase06-cicd.md
> +و اهمیت استفاده از آن آشنا خواهید شد. همچنین پروژهٔ خود را به CI/CD
زمان فعل دو جمله‌ی متوالی با یکدیگر هماهنگ نیست.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase06-cicd.md
> +- [What is CI/CD?(redhat) video](https://www.redhat.com/en/topics/devops/what-is-ci-cd)
در عنوان این لینک کلمه‌ی video آمده است در حالی که در این لینک ویدیوئی مشاهده نمی‌شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase06-cicd.md
> +## آشنایی با GitHub Actions و اضافه کردن CI/CD Pipeline به ریپازیتوری
کلمه‌ی ریپازیتوری قشنگ‌تر است که به انگلیسی نوشته شود.

2022-07-11 12:36 UTC, mostmand commented on docs/software-engineering/phase06-cicd.md
> +## آشنایی با GitHub Actions و اضافه کردن CI/CD Pipeline به ریپازیتوری
چون ما Azure DevOps استفاده می‌کنیم شاید بهتر باشد که Azure DevOps را آموزش دهیم البته GitHub Actions هم مزایای خودش رو داره.

2022-07-11 14:21 UTC, RAAvenger commented on docs/software-engineering/phase06-cicd.md
> +## آشنایی با GitHub Actions و اضافه کردن CI/CD Pipeline به ریپازیتوری
اصلاح شد

2022-07-11 14:23 UTC, RAAvenger commented on docs/software-engineering/phase06-cicd.md
> +- [What is CI/CD?(redhat) video](https://www.redhat.com/en/topics/devops/what-is-ci-cd)
اصلاح شد

2022-07-11 14:25 UTC, RAAvenger commented on docs/software-engineering/phase06-cicd.md
> +و اهمیت استفاده از آن آشنا خواهید شد. همچنین پروژهٔ خود را به CI/CD
اصلاح شد

2022-07-11 14:26 UTC, RAAvenger commented on docs/software-engineering/phase06-cicd.md
> +و اهمیت استفاده از آن آشنا خواهید شد. همچنین پروژهٔ خود را به CI/CD
اصلاح شد

2022-07-11 14:31 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +:::caution توجه
اصلاح شد

2022-07-12 12:41 UTC, RAAvenger commented on docs/software-engineering/phase01-simple-project.md
> +در این بخش یک موتور جستجوی ساده می‌نویسیم که متن حجیمی را به‌عنوان ورودی بگیرد، پردازش‌های لازم را روی آن انجام دهد تا در نهایت کاربر بتواند روی متن‌هایی که قبلا وارد شده بود، جستجو کند.
اصلاح شد

2022-07-12 13:08 UTC, RAAvenger commented on docs/software-engineering/phase03-c-sharp.md
> +در این فاز با زبان #C آشنا خواهید شد. همچنین چند برنامۀ ساده با این زبان خواهید نوشت.
اصلاح شد

2022-07-12 13:14 UTC, RAAvenger commented on docs/software-engineering/phase03-c-sharp.md
> +با اجرای دستور بالا باید عبارت `Hello World`
برای این کار باید یه کامپوننت react بزنیم که یه قسمتی به عنوان result بگیره
توی این مرحله فکر نکنم زمان کافی برای این کار رو داشته باشیم.

2022-07-12 13:14 UTC, RAAvenger commented on docs/software-engineering/phase03-c-sharp.md
> +با اجرای دستور بالا باید عبارت `Hello World`
چک کردم خود فریمورک نداشت

2022-07-12 13:27 UTC, RAAvenger commented on docs/software-engineering/phase03-c-sharp.md
> +توسعه دهنده نگران دریافت و اشتراک کدها نمی‌باشد چرا که خود NuGet
اصلاح شد

2022-07-12 13:29 UTC, RAAvenger commented on docs/software-engineering/phase03-c-sharp.md
> +```C#
اصلاح شد

2022-07-12 13:34 UTC, RAAvenger commented on docs/software-engineering/phase03-c-sharp.md
> +- [Console.ReadLine() Method in C#](<https://www.geeksforgeeks.org/console-readline-method-in-c-sharp/#:~:text=Console.-,ReadLine()%20Method%20in%20C%23,user%20presses%20the%20Enter%20key.>)
اصلاح شد

2022-07-12 14:01 UTC, RAAvenger commented on docs/software-engineering/phase04-unit-test.md
> +## تاثیر اصول SOLID بر Unit Tesing
در فاز clean code به این اصول پرداخته شد

2022-07-12 14:50 UTC, RAAvenger commented on docs/software-engineering/phase04-unit-test.md
> +کردن است که در آن، قسمتی از کد را با یک پیاده‌سازی دلخواه جایگزین می‌کنیم و از آن برای شبیه‌سازی یک عملیات واقعی استفاده می‌شود. معمولا Mock
اصلاح شد

2022-07-12 14:53 UTC, RAAvenger commented on docs/software-engineering/phase04-unit-test.md
> +و نحوۀ استفاده این تکنیک در زبان #C
اصلاح شد

2022-07-12 14:53 UTC, RAAvenger commented on docs/software-engineering/phase04-unit-test.md
> +- [Getting started with moq](https://riptutorial.com/moq)
اصلاح شد

2022-07-12 14:53 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +## بازنویسی پروژهٔ سرچ با زبان #C و با رویکرد TDD
اصلاح شد

2022-07-12 14:53 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +در این مرحله، پروژهٔ سرچ خود را که قبلاً جاوا نوشته‌اید را بعنوان یک library
اصلاح شد

2022-07-12 14:54 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +همچنین مراحل زیر را برای ساختن پروژهٔ خود دنبال کنید.
اصلاح شد

2022-07-12 14:54 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +### ساختن یک پروژهٔ Class Library
اصلاح شد

2022-07-12 14:54 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +در این مرحله یک پروژهٔ Net Class Library.
اصلاح شد

2022-07-12 14:55 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +در این مرحله یک پروژه تست با فریم‌ورک XUnit
اصلاح شد

2022-07-12 14:56 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +dotnet new XUnit -o .\SampleLibrary.Test
اصلاح شد

2022-07-12 14:57 UTC, RAAvenger commented on docs/software-engineering/phase05-tdd.md
> +کد پروژهٔ شما، در پروژهٔ Class Libraryای
اصلاح شد

2022-07-13 05:41 UTC, mostmand commented on docs/software-engineering/phase03-c-sharp.md
> +با اجرای دستور بالا باید عبارت `Hello World`
به نظرم همین که این جوری بذاری کفایت می‌کنه:
```
Hello World
```

2022-07-13 06:16 UTC, mostmand approved these changes

2022-07-13 12:49 UTC, RAAvenger commented on docs/software-engineering/phase03-c-sharp.md
> +با اجرای دستور بالا باید عبارت `Hello World`
اصلاح شد

2022-07-15 03:03 UTC, BijanEisapour requested changes
حجم عکس‌ها کاهش پیدا کنه

2022-07-15 06:23 UTC, merged