write dom document
Star-Academy/codestar-documents pull request #100
Opened 2024-07-07 12:38 UTC by SaveAsArTaZ

2024-07-08 09:19 UTC, dkhorasanizadeh requested changes

2024-07-08 09:19 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +![UI vs UX](./images/DOM.png)
تکست 
Alt
درست بشه.

2024-07-08 09:19 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +سندهای HTML به صورت سلسله مراتبی سازماندهی شده‌اند. این ساختار به برنامه‌نویسان و مرورگرها اجازه می‌دهد تا به راحتی اجزاء مختلف سند را پیدا و دستکاری کنند. در این ساختار، هر عنصر HTML یک **گره** (Nod
نامگذاری‌ها حتما یکپارچه باشن. یعنی یک جا نگیم پرونده و یک جا بگیم سند و یک جا بگیم داکیومنت.
(این رو توی این داک ندیدم ولی گفتم بگم که حتما بهش توجه ویژه بشه.)

2024-07-08 09:19 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +-   **گره ریشه** (Root Node): نود ریشه در سند HTML معمولاً `<html>` است که تمام عناصر دیگر سند به عنوان فرزندان آن قرار می‌گیرند.
اینجا نامگذاری یکپارچه نیست. یک جا گفتیم گره و بعد گفتیم نود.

2024-07-08 09:19 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +سندهای HTML به صورت سلسله مراتبی سازماندهی شده‌اند. این ساختار به برنامه‌نویسان و مرورگرها اجازه می‌دهد تا به راحتی اجزاء مختلف سند را پیدا و دستکاری کنند. در این ساختار، هر عنصر HTML یک **گره** (Nod
کلمات انگلیسی تو یک خط جدا قرار بگیرن. (مثل کانونشن داک‌های ستاره و برای خوانایی بیشتر مارکداون خام.)

2024-07-08 09:19 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +**ساختار DOM:**
اینجا ممکنه طرف تفاوت بین توضیح قبلی نودها و این رو درک نکنه و گیج بشه.

2024-07-08 09:19 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +-   **گره‌های نظر** (Comment Nodes): نمایانگر نظرات موجود در سند
نیازی نیست انقدر فارسی کنیم متن رو. اگر یک واژه‌ای تو ادبیات برنامه نویسا به همون صورت انگلیسی شناخته شده و استفاده می‌شه همون رو بنویسیم.

2024-07-08 14:44 UTC, SaveAsArTaZ commented on docs/frontend/phase10-dom.md
> +-   **گره‌های نظر** (Comment Nodes): نمایانگر نظرات موجود در سند
done

2024-07-08 14:44 UTC, SaveAsArTaZ commented on docs/frontend/phase10-dom.md
> +![UI vs UX](./images/DOM.png)
نمیفهمم

2024-07-08 14:49 UTC, SaveAsArTaZ commented on docs/frontend/phase10-dom.md
> +سندهای HTML به صورت سلسله مراتبی سازماندهی شده‌اند. این ساختار به برنامه‌نویسان و مرورگرها اجازه می‌دهد تا به راحتی اجزاء مختلف سند را پیدا و دستکاری کنند. در این ساختار، هر عنصر HTML یک **گره** (Nod
اینو برای لیست نمیشه انجام داد ولی برای بقیش انجام دادم

2024-07-09 11:09 UTC, dkhorasanizadeh approved these changes

2024-07-09 11:09 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +![UI vs UX](./images/DOM.png)
https://dev.to/stephencweiss/markdown-image-titles-and-alt-text-5fi1

2024-07-09 11:09 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +HTML
Indent

2024-07-09 11:09 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +-    **Comment Nodes**: نمایانگر نظرات موجود در سند
کامنت رو همون کامنت بنویسیم. نیازی به ترجمه نیست.

2024-07-09 11:11 UTC, dkhorasanizadeh commented on docs/frontend/phase10-dom.md
> +HTML
روی کل داکیومنت یه فرمت بزن که IDE ایندنت‌ها رو اوکی کنه.

2024-07-09 11:55 UTC, SaveAsArTaZ commented on docs/frontend/phase10-dom.md
> +-    **Comment Nodes**: نمایانگر نظرات موجود در سند
done

2024-07-09 12:04 UTC, merged