Add networking doc
Star-Academy/codestar-documents pull request #109
Opened 2024-07-10 15:27 UTC by dkhorasanizadeh

2024-07-11 07:28 UTC, RAAvenger requested changes
دستت درد نکنه و خسته نباشی
دوتا چیز چندبار تکرار شدن، یکی اینکه نوشتیم «. و» و یکی اینکه نوشتیم «این لینک»، «این ویدئو» که بهتره اسم خود ویدئو/لینک رو بنویسیم.

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +تا اینجای کار متوجه شدیم که چرا به شبکه‌های کامپیوتری نیاز داریم و فرض کردیم که کامپیوترها می‌توانند با وصل شدن به یک سیم و تغییر ولتاژ آن سیم برای یکدیگر داده ارسال کنند. اما همه چیز به این سادگی نی
> . اما همه چیز به این سادگی نیست

اما این کار چالش‌هایی دارد.

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +درباره روش‌های ممکن برای اتصال چندین کامپیوتر به هم فکر کرده و درباره مزایا و معایب هر روش با هم‌گروهی خود صحبت کنید.
این تسکه
خوبه تسکا رو توی یه قالبی بذاریم که مشخص تر باشن

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +و سپس وقتی که با پروتکل
> و سپس

«و» لازمه؟

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +به این سوالات فکر کرده و سعی کنید راه حلی برای آن‌ها پیدا کنید. و سپس با تماشای
> پیدا کنید. و سپس

کلا یه سرچ بزن برای «. و»ها و درستشون کنیم

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +[این ویدیو](https://www.youtube.com/watch?v=5WfiTHiU4x8&t=890s)
جذاب تره که اسم ویدئو رو بذاریم و بگیم «ویدئوی 
```
[video name](link)
```
«

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +:::info نکته
میتونی این رو 
tip
کنی

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +معماری
این عنوانه رو یکم بولدش کنیم (یا هدرش کنیم)

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +حتما اسم Server را زیاد شنیده‌اید، اما این اسم واقعا به چه معنی است؟
Server
بره خط خودش

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +معمولا خدماتی که به کاربرها ارائه داده می‌شود، بوسیله یک برنامه خاص پشتیبانی می‌شود که منطق و داده‌های خاص خودش ار دارد. خیلی وقت‌ها، این منطق و داده‌ها با کاربران به اشتراک گذاشته نمی‌شوند، بلکه بر
>  ار

را

2024-07-11 07:28 UTC, RAAvenger commented on docs/devops/02-network.md
> +به ما اجازه می‌دهد چنین کاری را انجام دهیم. با جست‌وجو در اینترنت با این ابزار آشنا شده و
> با جست‌وجو در اینترنت

ایده‌ی این رو درک میکنم ولی به نظرم یه لینک خلاصه بدیم و اگر خواستن بیشتر عمیق بشن خودشون برن بگردن

برای اینکه برن بگردن هم میشه تسکایی داد که جوابشون توی لینکایی که خودمون دادیم نباشه

2024-07-13 11:23 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +با بوجود اومدن کامپیوترها، آن‌ها وظیفه انجام کارهای تکراری و محاسبات پیچیده را بر عهده گرفته و انجام کارهایی که قبلا برای ما سخت بود را ساده کردند. با گسترش استفاده از آن‌ها، نیاز جدیدی بوجود آمد. دا
این جمله تاکید روی فلسفه 
Computers Perform Repetitive Tasks, People Solve Problems
هستش.

2024-07-13 11:24 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +امروزه شبکه‌های کامپیوتری در همه بخش‌های زندگی ما نقش داشته و اکثر محصولات و سرویس‌های کامپیوتری از طریق بزرگترین شبکه کامپیوتری موجود یا همان اینترنت به دست کاربرها می‌رسند. و به همین خاطر شناخت این
Fix

2024-07-13 11:24 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +امروزه شبکه‌های کامپیوتری در همه بخش‌های زندگی ما نقش داشته و اکثر محصولات و سرویس‌های کامپیوتری از طریق بزرگترین شبکه کامپیوتری موجود یا همان اینترنت به دست کاربرها می‌رسند. و به همین خاطر شناخت این
Fix

2024-07-13 11:24 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +زمانی که شما با یک فرد جدید ملاقات می‌کنید، اول سلام و احوالپرسی کرده و بعد از این، خودتان را معرفی می‌کنید. این رفتار شما یک قانون اجتماعی است. کامپیوترها هم برای ارتباط با هم به قوانینی نیاز دارند
Fix

2024-07-13 11:24 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +زمانی که شما با یک فرد جدید ملاقات می‌کنید، اول سلام و احوالپرسی کرده و بعد از این، خودتان را معرفی می‌کنید. این رفتار شما یک قانون اجتماعی است. کامپیوترها هم برای ارتباط با هم به قوانینی نیاز دارند
Fix

2024-07-13 11:27 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +تا اینجای کار متوجه شدیم که چرا به شبکه‌های کامپیوتری نیاز داریم و فرض کردیم که کامپیوترها می‌توانند با وصل شدن به یک سیم و تغییر ولتاژ آن سیم برای یکدیگر داده ارسال کنند. اما همه چیز به این سادگی نی
Fix

2024-07-13 11:32 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +تا اینجای کار متوجه شدیم که چرا به شبکه‌های کامپیوتری نیاز داریم و فرض کردیم که کامپیوترها می‌توانند با وصل شدن به یک سیم و تغییر ولتاژ آن سیم برای یکدیگر داده ارسال کنند. اما همه چیز به این سادگی نی
این یکم جمله اپیک تریه.

2024-07-13 11:33 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +درباره روش‌های ممکن برای اتصال چندین کامپیوتر به هم فکر کرده و درباره مزایا و معایب هر روش با هم‌گروهی خود صحبت کنید.
Fix

2024-07-13 11:34 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +و سپس وقتی که با پروتکل
Fix

2024-07-13 11:43 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +به این سوالات فکر کرده و سعی کنید راه حلی برای آن‌ها پیدا کنید. و سپس با تماشای
Fix

2024-07-13 11:46 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +حتما اسم Server را زیاد شنیده‌اید، اما این اسم واقعا به چه معنی است؟
Fix

2024-07-13 11:46 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +معماری
Fix

2024-07-13 11:46 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +:::info نکته
Fix

2024-07-13 11:46 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +معمولا خدماتی که به کاربرها ارائه داده می‌شود، بوسیله یک برنامه خاص پشتیبانی می‌شود که منطق و داده‌های خاص خودش ار دارد. خیلی وقت‌ها، این منطق و داده‌ها با کاربران به اشتراک گذاشته نمی‌شوند، بلکه بر
Fix

2024-07-13 11:47 UTC, dkhorasanizadeh commented on docs/devops/02-network.md
> +به ما اجازه می‌دهد چنین کاری را انجام دهیم. با جست‌وجو در اینترنت با این ابزار آشنا شده و
این هم از جنس همون تسکاست در عمل. کلا nc ابزار ساده‌ایه و میتونن سریع به پاسخ این جست‌وجوشون برسن.

2024-07-15 06:36 UTC, RAAvenger approved these changes

2024-07-15 08:38 UTC, merged