05-golang document completed
Star-Academy/codestar-documents pull request #114
Opened 2024-07-10 19:43 UTC by MohammadHDehghani

2024-07-15 09:15 UTC, dkhorasanizadeh requested changes

2024-07-15 09:15 UTC, dkhorasanizadeh commented on docs/devops/05-golang.md
> +به عنوان عضوی از یک تیم دواپس، اغلب نیاز داریم تا به توسعه، اتوماتیک سازی و یا سفارشی سازی برخی از فرایندها بپردازیم. این کار با استفاده از زبان‌های برنامه‌نویسی و یا اسکریپت نویسی صورت می‌گیرد. یکی
اینجا دواپس بشه دوآپس یا 
DevOps

2024-07-15 09:15 UTC, dkhorasanizadeh commented on docs/devops/05-golang.md
> +Terraform ،
لطفا داکر و کوبرنیتیز رو هم بنویس اونا خیلی تو چشم ترن

2024-07-15 09:15 UTC, dkhorasanizadeh commented on docs/devops/05-golang.md
> +[Golang for Devops](https://www.scaler.com/topics/devops-tutorial/golang-for-devops/)
این‌ها اگر لیست مارکداون بشن قشنگ‌ترن

2024-07-15 09:15 UTC, dkhorasanizadeh commented on docs/devops/05-golang.md
> +کمک بگیرید.
یه مینی پروژه هم اگر اینجا اضافه کنی خوبه. ترجیحا یه چیزی باشه که تو فازای بعدی بگیم داکرایزش کنن و بعد هم براش 
CI/CD
بنویسن

2024-07-15 09:15 UTC, dkhorasanizadeh commented on docs/devops/05-golang.md
> +ک زبان برنامه نویسی سبک است و بسیاری از ابزارهای دواپس مانند
اینجا یه ک اضافه‌ست

2024-07-15 09:15 UTC, dkhorasanizadeh commented on docs/devops/05-golang.md
> +## قواهد نام‌گذاری در GoLang
اینجا اگر بشه 
Go
که با بقیه داک یکپارچه باشه به نظرم بهتره

2024-07-16 00:47 UTC, MohammadHDehghani commented on docs/devops/05-golang.md
> +به عنوان عضوی از یک تیم دواپس، اغلب نیاز داریم تا به توسعه، اتوماتیک سازی و یا سفارشی سازی برخی از فرایندها بپردازیم. این کار با استفاده از زبان‌های برنامه‌نویسی و یا اسکریپت نویسی صورت می‌گیرد. یکی
کل "دواپس" ها به "دوآپس" تبدیل شدند

2024-07-16 00:48 UTC, MohammadHDehghani commented on docs/devops/05-golang.md
> +Terraform ،
اضافه شدند

2024-07-16 00:48 UTC, MohammadHDehghani commented on docs/devops/05-golang.md
> +[Golang for Devops](https://www.scaler.com/topics/devops-tutorial/golang-for-devops/)
بولت شدند

2024-07-16 00:49 UTC, MohammadHDehghani commented on docs/devops/05-golang.md
> +ک زبان برنامه نویسی سبک است و بسیاری از ابزارهای دواپس مانند
این یک بود، ی از قلم افتاد که اضافه شد

2024-07-16 00:49 UTC, MohammadHDehghani commented on docs/devops/05-golang.md
> +## قواهد نام‌گذاری در GoLang
عوض شد

2024-07-19 15:41 UTC, closed without merging