Feature/review software phase 1 6
Star-Academy/codestar-documents pull request #116
Opened 2024-07-14 12:29 UTC by tahadavari

2024-07-15 08:49 UTC, dkhorasanizadeh approved these changes

2024-07-15 16:35 UTC, AliSK81 requested changes

2024-07-15 16:35 UTC, AliSK81 commented on docs/software-engineering/phase02-full-text-search-project.md
> +Dotnet
.NET

2024-07-15 16:35 UTC, AliSK81 commented on docs/software-engineering/phase05-tdd.md
> +قابلیتی را اضافه کنید که بتوان به صورت عبارتی جست و جو را انجام داد.
قابلیتی اضافه کنید که امکان جستجوی عبارت نیز فراهم شود.
بهتر نیست؟

2024-07-16 09:15 UTC, tahadavari commented on docs/software-engineering/phase02-full-text-search-project.md
> +Dotnet
چون نقطه داره اولش جابجا میشن نقطه و net

2024-07-16 09:17 UTC, tahadavari commented on docs/software-engineering/phase04-unit-test.md
> +برای چه بخشی تست ننوشته بودید و دلیل آن چه چیزی بودی؟
متوجه نشدم 
با منتورشون و خودشون صحبت میکنند

2024-07-16 15:07 UTC, AliSK81 commented on docs/software-engineering/phase04-unit-test.md
> +برای چه بخشی تست ننوشته بودید و دلیل آن چه چیزی بودی؟
حله
این جمله:
"برای چه بخشی تست ننوشته بودید و دلیل آن چه چیزی بودی؟"
بودی یا بوده است؟

2024-07-16 15:08 UTC, AliSK81 approved these changes

2024-07-16 18:04 UTC, merged