[ADD] RxJS & HTTP & Angular Routing docs
Star-Academy/codestar-documents pull request #159
Opened 2024-08-02 08:52 UTC by BehnamBorhani

2024-08-02 15:36 UTC, dkhorasanizadeh commented
لطفا فولدر .idea رو پاک کن و به .gitignore هم اضافش کن.

2024-08-02 15:41 UTC, dkhorasanizadeh requested changes

2024-08-02 15:41 UTC, dkhorasanizadeh commented on docs/frontend/phase08-http.md
> +سرور می‌تواند به واسطه‌ها و کلاینت‌ها در مورد این که کش کردن چطور و برای چه مدتی انجام شود، دستورالعمل بدهد.
اینجا یکم جملات حالت جالبی ندارن و به نظرم میتونن بهتر بشن.

2024-08-02 15:41 UTC, dkhorasanizadeh commented on docs/frontend/phase08-http.md
> +و به سند امکان دهند که یک لحاف چهل تکه از اطلاعات باشد که از دامنه‌های مختلف تأمین می‌شوند.
باز اینجا هم لحاف چهل تکه این وسط یکم عجیبه. کلا هم رهایی از قید Origin یکم معنی رو نمیرسونه.

2024-08-02 15:41 UTC, dkhorasanizadeh commented on docs/frontend/phase08-http.md
> +را به حالت سرور پیوند دهید.
اینجا حالت سرور منظور استیته؟

2024-08-02 15:41 UTC, dkhorasanizadeh commented on docs/frontend/phase08-http.md
> +این وضعیت نه تنها برای مدیریت سبد خرید فروشگاه‌های آنلاین مفید است،
اینجا بدون کانتکست سبد یهو اومد وسط.

2024-08-03 07:10 UTC, SaveAsArTaZ approved these changes

2024-08-03 07:59 UTC, dkhorasanizadeh approved these changes

2024-08-03 08:37 UTC, merged