Test Document
Star-Academy/codestar-documents pull request #98
Opened 2024-07-05 11:27 UTC by Pouya2781

Test Document

2024-07-07 12:54 UTC, SaveAsArTaZ requested changes

2024-07-07 12:54 UTC, SaveAsArTaZ commented on docs/frontend/phase09-unit-testing.md
> +در Angular فزایند Moking شامل component، service، directive و ... می‌شود که برای اطلاعات بیشتر درباره آن می‌توانید از لینک‌های زیر استفاده کنید:
نوشتی فزایند

2024-07-07 12:54 UTC, SaveAsArTaZ commented on docs/frontend/phase09-unit-testing.md
> +      "builder": "@angular-builders/custom-webpack:browser",
کاستوم وبپک چرا ؟‌
وب پک هم قدیمیه احتمالا بچه ها از vite استفاده کنند

2024-07-07 12:54 UTC, SaveAsArTaZ commented on docs/frontend/phase09-unit-testing.md
> +
اینارو خود سایپرس انجام میده رو پروژت

2024-07-07 12:54 UTC, SaveAsArTaZ commented on docs/frontend/phase09-unit-testing.md
> +
بهتره بگی این کارا اعمال میشه

2024-07-07 18:17 UTC, Pouya2781 commented on docs/frontend/phase09-unit-testing.md
> +
من اینو الان تو خود داک cypress دیدم فقط یکم تغییرش دادم

![image](https://github.com/Star-Academy/codestar-documents/assets/74897023/917b6a0e-a70c-4668-8433-15031af357a0)

2024-07-10 08:54 UTC, SaveAsArTaZ approved these changes

2024-07-11 17:02 UTC, dkhorasanizadeh requested changes

2024-07-11 17:02 UTC, dkhorasanizadeh commented on docs/frontend/phase09-test.md
> +An Integral Part Of The Software Development Process
چرا یهویی انگلیسی میشه؟

2024-07-11 17:02 UTC, dkhorasanizadeh commented on docs/frontend/phase09-test.md
> +تست بنوسید، پس از نوشتن به منتور خود تست‌های خود را نمایش دهید.
```suggestion
برای کامپوننت‌هایی که در قسمت
Angular
توسعه دادید به ترتیب برای هرکدام 2 عدد
Unit, Integration
و
E2E
تست بنوسید، پس از نوشتن به منتور خود تست‌های خود را نمایش دهید.
```
برای هریک از کامپوننت‌هایی که در قسمت
Angular
توسعه دادید 2 تست
Unit,
2 تست 
Integration
و 2 تست
E2E
بنویسید.

2024-07-13 06:37 UTC, SaveAsArTaZ commented on docs/frontend/phase09-test.md
> +چگونه می‌توانید از صحت کارکرد قسمت‌های وابسته اطمینان حاصل کنید؟
عوض کردم کلن متنشو

2024-07-13 06:40 UTC, SaveAsArTaZ approved these changes

2024-07-13 06:40 UTC, SaveAsArTaZ commented on docs/frontend/phase09-test.md
> +-   چگونه می‌توان فهمید چند درصد از کدهای موجود تست شده‌اند؟
اینم عوض کردم کلن

2024-07-13 06:40 UTC, SaveAsArTaZ commented on docs/frontend/phase09-test.md
> +An Integral Part Of The Software Development Process
اینم فارسیش میکنم

2024-07-13 06:51 UTC, dkhorasanizadeh approved these changes

2024-07-13 07:16 UTC, SaveAsArTaZ approved these changes

2024-07-13 07:17 UTC, merged