Typescript doc
Star-Academy/codestar-documents pull request #99
Opened 2024-07-05 17:36 UTC by Pouya2781

Typescript doc

2024-07-07 13:10 UTC, SaveAsArTaZ requested changes

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [Altcademy - Primitives in TypeScript](https://www.altcademy.com/blog/what-are-primitives-in-typescript/)
تحریم هست این سایت

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [W3schools - TypeScript Simple Types](https://www.w3schools.com/typescript/typescript_simple_types.php)
این خوب نیست

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [W3schools - Arrays](https://www.w3schools.com/typescript/typescript_arrays.php)
به جای w3 از این سایت استفاده کن 
https://developer.mozilla.org/en-US/docs/Glossary/TypeScript

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [W3schools - Arrays](https://www.w3schools.com/typescript/typescript_arrays.php)
برای همشون

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [TypeScript - Interfaces](https://www.typescriptlang.org/docs/handbook/interfaces.html)
بنظرم ریسورس های اینترفیس زیادن کمش کن ولی بهترینشو بذار و حواست باشه فیلتر یا تحریم نباشه

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [Geeksforgeeks - TypeScrtip Type Aliases](https://www.geeksforgeeks.org/typescript-aliases-type/)
احتمالا گیگز فور گیگز هم تحریم یا فیلتر شده از سایت جایکزین استفاده کن و همچنین نوشتی typescrtip

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [W3schools - Basic Generics](https://www.w3schools.com/typescript/typescript_basic_generics.php)
زیاده رفرنسش کمش کن ولی اولی مثلا خوب بود دوتا بذار

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +- [Refine - TypeScript Decorators in Brief](https://refine.dev/blog/typescript-decorators/)
سومی نمیاد بالا و حذف بشه زیاده

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +  greet(): void;
یه متغیر پاس بده که بفهمه ابرستکشن چیه

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +  greet() {
اینجا هم متغیره رو پاس بده

2024-07-07 13:10 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +number: برای اعداد استفاده می‌شود، مانند اعداد صحیح و اعشاری. <br></br>
از سایت markdown table generator برای ساخت تیبل استفاده کن

2024-07-11 17:08 UTC, dkhorasanizadeh approved these changes

2024-07-11 17:08 UTC, dkhorasanizadeh commented on docs/frontend/phase10-typescript.md
> +تصور کنید در یک پروژه‌ی بزرگ جاوااسکریپت کار می‌کنید. همان‌طور که کد شما بزرگ‌تر و پیچیده‌تر می‌شود، مشکلات مختلفی پدیدار می‌شوند.
```suggestion
بر روی یک پروژه بزرگ
```

2024-07-11 17:08 UTC, dkhorasanizadeh commented on docs/frontend/phase10-typescript.md
> +تصور کنید در یک پروژه‌ی بزرگ جاوااسکریپت کار می‌کنید. همان‌طور که کد شما بزرگ‌تر و پیچیده‌تر می‌شود، مشکلات مختلفی پدیدار می‌شوند.
```suggestion
همانطور که کدبیس شما بزرگ‌تر و پیجیده‌تر...
```

2024-07-11 17:08 UTC, dkhorasanizadeh commented on docs/frontend/phase10-typescript.md
> +-   انواع تایپ‌ها در
اینکه طرف بدونه از الان میخواد بفهمه انواع تایپ چیا هستن خیلی به کارش نمیاد. بهتره که به جای این‌ها همون توضیحات اولیه (که به طور کلی خیلی عالی هستن) رو بیشتر بهشون بپردازیم.

2024-07-11 17:08 UTC, dkhorasanizadeh approved these changes

2024-07-11 17:09 UTC, dkhorasanizadeh approved these changes

2024-07-13 07:17 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +---
phase11 بکن که با من کانفلیکت نخوری

2024-07-13 07:18 UTC, SaveAsArTaZ approved these changes

2024-07-13 07:20 UTC, SaveAsArTaZ requested changes

2024-07-13 07:20 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +number: برای اعداد استفاده می‌شود، مانند اعداد صحیح و اعشاری. <br></br>
این انجام نشده

2024-07-13 07:21 UTC, SaveAsArTaZ approved these changes

2024-07-13 07:21 UTC, SaveAsArTaZ commented on docs/frontend/phase10-typescript.md
> +---
دمت گرم داکیومنتت خوبه

2024-07-13 10:00 UTC, merged